version: '3.8'

services:
  app:
    container_name: scooter
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/scooter:/app

    stdin_open: true
    tty: true
  #server:
