build:
    nodes:
        analysis:
            environment:
                php:
                    version: 7.4
                node:
                    version: 20.5.1
        coverage:
          tests:
            paths:
              - "./tests"

    tests:
        override:
          - command: 'npm install'
          - command: 'npm run test'
          - command: 'scrutinizer-clover coverage/clover.xml'

filter:
  excluded_paths: [coverage/*]
